spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/qr_db?useUnicode=true&characterEncoding=utf-8&use
    url: jdbc:mysql://localhost:3306/qr_db?useUnicode=true&characterEncoding=utf-8&use
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
#  ????
logging:
  level:
    com.lfg.qr_day1.service: debug
