spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/qr_db?useUnicode=true&characterEncoding=utf-8&use
    url: jdbc:mysql://114.132.232.133:3306/qr_db
#    url: jdbc:mysql://20.187.89.187:3306/qr_db
    username: qr_db
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
# 日志
logging:
  level:
    com.lfg.qr_day1.service: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）