# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven update file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@master
      with:
        java-version: 8
        distribution: "adopt"
        cache: maven
    - name: Build with Maven
      run: mvn clean package --file pom.xml
    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        username: ${{ secrets.SERVER_SSH_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        password: ${{ secrets.SERVER_SSH_PASS }}
        source: "target/rongxiaotong-backend-0.0.1-SNAPSHOT.jar"
        rm: true
        target: "/www/wwwroot/target"
    - name: Deploy
      uses: appleboy/ssh-action@master
      timeout-minutes: 10  # 增加超时限制为 10 分钟
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        username: ${{ secrets.SERVER_SSH_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        password: ${{ secrets.SERVER_SSH_PASS }}
        command_timeout: 20s
        script:  |
          cd /www/wwwroot/target/target
          if pgrep -f rongxiaotong-backend-0.0.1-SNAPSHOT.jar > /dev/null; then
          pgrep -f rongxiaotong-backend-0.0.1-SNAPSHOT.jar | xargs -r kill -9
          else
          echo "Process not found, no need to kill."
          fi
          nohup /usr/local/btjdk/jdk8/bin/java -jar /www/wwwroot/target/target/rongxiaotong-backend-0.0.1-SNAPSHOT.jar --server.port=8080 >/dev/null 2>&1 &
          pwd
          exit